# Generated by Django 4.0.4 on 2022-04-19 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Posting', '0002_alter_mainpost_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpost',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
