# Generated by Django 4.0.4 on 2022-04-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posting', '0006_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
