# Generated by Django 4.0.4 on 2022-04-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posting', '0009_alter_post_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='createdDate',
            field=models.DateTimeField(null=True),
        ),
    ]
