# Generated by Django 4.0.4 on 2022-04-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posting', '0011_rename_text_post_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='text',
        ),
    ]
