# Generated by Django 4.0.4 on 2022-04-19 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posting', '0014_alter_post_channel_alter_post_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='channel',
        ),
    ]
