# Generated by Django 4.0.4 on 2022-04-19 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Channels', '0003_alter_channel_username'),
        ('Posting', '0016_post_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='Channels.channel'),
        ),
    ]
