# Generated by Django 4.0.4 on 2022-04-19 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posting', '0017_alter_post_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='channel',
            new_name='channel_id',
        ),
    ]
