# Generated by Django 4.0.4 on 2022-04-19 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posting', '0018_rename_channel_post_channel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
    ]
