# Generated by Django 4.0.4 on 2022-04-19 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posting', '0019_remove_post_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='channel_id',
            new_name='channel',
        ),
    ]
