# Generated by Django 4.0.4 on 2022-04-19 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_customuser_bio_customuser_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
