# Generated by Django 4.0.4 on 2022-04-19 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='username',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='Channel_Creator_Username', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
