# Generated by Django 4.0.4 on 2022-04-19 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Channels', '0003_alter_channel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='username',
        ),
    ]
