# Generated by Django 4.0.4 on 2022-04-19 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Channels', '0006_remove_channel_username_channel_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='user_id',
            new_name='user',
        ),
    ]
