# Generated by Django 4.0.4 on 2022-04-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Channels', '0007_rename_user_id_channel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='urlName',
            field=models.CharField(default='default_url_name', max_length=50),
            preserve_default=False,
        ),
    ]
