# Generated by Django 4.0.4 on 2022-04-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Channels', '0008_channel_urlname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='urlName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
