# Generated by Django 4.0.4 on 2022-04-22 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Channels', '0009_alter_channel_urlname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='urlName',
            new_name='urlname',
        ),
    ]
