# Generated by Django 4.0.4 on 2022-04-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Channels', '0010_rename_urlname_channel_urlname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='urlname',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
