# Generated by Django 4.0.4 on 2022-04-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Channels', '0011_alter_channel_urlname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='urlname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
